name = "jira-api-proxy"
main = "worker-jira-api.js"
compatibility_date = "2024-10-23"

# Variáveis de ambiente (Jira)
# Configure via 'wrangler secret put' se necessário, mas o worker já lê de env vars

[[kv_namespaces]]
binding = "RESERVATIONS_KV"
id = "c4b76fc7817f4778b86a96c1cb59a609"
preview_id = "c4b76fc7817f4778b86a96c1cb59a609"
